"""Selected level-1 Storm Druid and compact public encounter fixtures.

Sources: https://2e.aonprd.com/Classes.aspx?ID=34,
https://2e.aonprd.com/DruidicOrders.aspx, https://2e.aonprd.com/Spells.aspx?ID=1860,
and https://2e.aonprd.com/Feats.aspx?ID=4712.
"""

from .items import ItemInstance
from .druid import AnimalEmpathyRecord
from .investigator_content import GUARD_DOG_KNOWLEDGE
from .model import AttackDefinition, CreatureDefinition, CreaturePlacement, EncounterSetup, HealthMode, Position, PreparedSpellDefinition, SpontaneousSpellDefinition
from .wizard_content import BATTLE_MAGIC_WIZARD

STORM_DRUID = CreatureDefinition(
    definition_id="storm_druid_level_1", name="Level 1 Storm Druid", hp=18, ac=16, perception=7, land_speed_ft=30,
    attacks=(AttackDefinition("staff", "Staff", 4, 5, frozenset({"attack", "melee", "two_hand_d8"}), "bludgeoning", (4,), 1, item_id="staff"), AttackDefinition("fist", "Fist", 4, 5, frozenset({"attack", "melee", "agile", "finesse", "nonlethal", "unarmed"}), "bludgeoning", (4,), 1)),
    kind="pc", health_mode=HealthMode.PC, vision="ordinary", hero_points=1,
    ability_modifiers=(("strength", 1), ("dexterity", 2), ("constitution", 2), ("intelligence", 0), ("wisdom", 4), ("charisma", 0)),
    skills=(("acrobatics", "trained", 5), ("athletics", "trained", 4), ("nature", "trained", 7), ("diplomacy", "trained", 3), ("medicine", "trained", 7), ("society", "trained", 3), ("survival", "trained", 7), ("academia_lore", "trained", 3)),
    saves=(("fortitude", "trained", 5), ("reflex", "trained", 5), ("will", "expert", 7)),
    proficiencies=(("perception", "trained"), ("fortitude", "trained"), ("reflex", "trained"), ("will", "expert"), ("simple_weapons", "trained"), ("unarmed_attacks", "trained"), ("unarmored_defense", "trained"), ("light_armor", "trained"), ("medium_armor", "trained"), ("spell_attack", "trained"), ("spell_dc", "trained"), ("class_dc", "trained")),
    level=1, ancestry="Human", heritage="Versatile Human", background="Scholar", class_name="Druid", languages=("Common", "Wildsong", "Elven"), class_dc=17, spell_attack=7, spell_dc=17, spell_attribute="wisdom", spell_tradition="primal",
    prepared_spells=(PreparedSpellDefinition("druid_electric_arc", "primal_cantrip", "electric_arc", cantrip=True), PreparedSpellDefinition("druid_guidance", "primal_cantrip", "guidance", cantrip=True), PreparedSpellDefinition("druid_stabilize", "primal_cantrip", "stabilize", cantrip=True), PreparedSpellDefinition("druid_tangle_vine", "primal_cantrip", "tangle_vine", cantrip=True), PreparedSpellDefinition("druid_light", "primal_cantrip", "light", cantrip=True), PreparedSpellDefinition("druid_heal_one", "primal_rank_1", "heal"), PreparedSpellDefinition("druid_runic_weapon_two", "primal_rank_1", "runic_weapon")),
    focus_spells=(SpontaneousSpellDefinition("tempest_surge", 1),), focus_source="storm_order", focus_points=1, focus_capacity=1,
    abilities=("shield_block", "wildsong", "voice_of_nature", "animal_empathy", "storm_born", "tempest_surge", "storm_druid_preparation", "assurance_nature"), feats=("Fleet", "Natural Skill", "Assurance (Nature)", "Storm Born", "Animal Empathy"), held_items=("staff", "steel_shield"), worn_items=("leather_armor",), item_instances=(ItemInstance("staff", "staff"), ItemInstance("steel_shield", "steel_shield", hp=20)),
    sheet_notes=("Human ancestry HP 8 plus Druid 8 + Constitution 2 yields 18 HP. Natural Skill is the level-1 Human ancestry feat and selects Athletics and Society; Versatile Human selects Fleet as its qualifying general feat, raising Speed to 30 feet.", "Scholar boosts Wisdom and trains Nature, Academia Lore, and Assurance (Nature). Druid already trains Nature, so its replacement trained skill is Medicine.", "Leather armor supplies the authored AC 16 with Dexterity +2 and trained light armor.", "Storm order grants trained Acrobatics, Storm Born, and Tempest Surge.", "Voice of Nature selects Animal Empathy: rudimentary questions and answers plus Diplomacy with animals; it grants no obedience or combat commands.", "Shield Block is available with the held steel shield (Hardness 5; HP 20; BT 10).", "The finite prepared primal choices are five cantrips and Heal/Runic Weapon for each rank-1 slot; duplicate rank-1 choices are legal.", "Anathema is an explicit GM-adjudicated sheet fact; this encounter has no violation simulator."),
)

_DOG_QUESTION = AnimalEmpathyRecord("guard_dog_kennel", "dog", "Who has been feeding and directing you?", "wary but not coerced", "indifferent", 15, 17, ("The dog barks and withdraws.", "The dog gives no useful response.", "The dog recognizes a handler's red scarf and the kennel gate.", "The dog eagerly indicates the red scarf and kennel gate."), ("The dog refuses the request and growls.", "The dog watches but does not comply.", "The dog allows a careful approach and leads toward the kennel gate.", "The dog trusts the request and leads directly to the kennel gate."))
STORM_DRUID_SETUP = EncounterSetup("storm_druid_vs_guard_dog", "Storm Druid vs. Guard Dog", 7, 5, (CreaturePlacement("druid", STORM_DRUID.definition_id, "Storm Druid", "blue", Position(1, 2)), CreaturePlacement("dog", "guard_dog_mc2924", "Guard Dog", "red", Position(4, 2))), knowledge=(GUARD_DOG_KNOWLEDGE,), animal_empathy=(_DOG_QUESTION,))
STORM_DRUID_NEXT_SETUP = EncounterSetup("storm_druid_next_guard_dog", "Storm Druid Next Guard Dog", 7, 5, (CreaturePlacement("druid", STORM_DRUID.definition_id, "Storm Druid", "blue", Position(1, 2)), CreaturePlacement("next_dog", "guard_dog_mc2924", "Next Guard Dog", "red", Position(4, 2))))
STORM_DRUID_SAVE_SETUP = EncounterSetup("storm_druid_tempest_save", "Storm Druid Tempest Surge Save", 7, 5, (CreaturePlacement("druid", STORM_DRUID.definition_id, "Storm Druid", "blue", Position(1, 2)), CreaturePlacement("wizard_target", BATTLE_MAGIC_WIZARD.definition_id, "Wizard Target", "red", Position(4, 2))))
STORM_DRUID_WEATHER_SETUP = EncounterSetup("storm_druid_weather", "Storm Druid in Weather", 7, 5, (CreaturePlacement("druid", STORM_DRUID.definition_id, "Storm Druid", "blue", Position(1, 2)), CreaturePlacement("dog", "guard_dog_mc2924", "Guard Dog", "red", Position(4, 2))), weather_ranged_spell_attack_circumstance_penalty=2, weather_perception_circumstance_penalty=2, weather_concealment=True)
_ALLY_DOG_QUESTION = AnimalEmpathyRecord("kennel_guide", "animal_dog", "Will you guide us to the kennel gate?", "wary but not coerced", "indifferent", 15, 17, ("The dog barks and withdraws.", "The dog gives no useful response.", "The dog recognizes the kennel gate and watches the path.", "The dog eagerly indicates the kennel gate."), ("The dog refuses the request and growls.", "The dog watches but does not comply.", "The dog allows a careful approach and leads toward the kennel gate.", "The dog trusts the request and leads directly to the kennel gate."))
STORM_DRUID_SOCIAL_SETUP = EncounterSetup("storm_druid_animal_empathy", "Storm Druid and Kennel Dog", 7, 5, (CreaturePlacement("druid", STORM_DRUID.definition_id, "Storm Druid", "blue", Position(1, 2)), CreaturePlacement("animal_dog", "guard_dog_mc2924", "Kennel Dog", "blue", Position(2, 2)), CreaturePlacement("hostile_dog", "guard_dog_mc2924", "Hostile Guard Dog", "red", Position(4, 2))), animal_empathy=(_ALLY_DOG_QUESTION,))
