"""The approved level-1 Justice Champion content slice."""

from __future__ import annotations

from .items import ItemInstance
from .model import (
    AttackDefinition,
    CreatureDefinition,
    CreaturePlacement,
    EncounterSetup,
    HealthMode,
    Position,
    SpontaneousSpellDefinition,
)


JUSTICE_CHAMPION = CreatureDefinition(
    definition_id="justice_champion_iomedae_level_1",
    name="Level 1 Justice Champion of Iomedae",
    hp=20,
    ac=18,
    perception=3,
    land_speed_ft=25,
    attacks=(
        AttackDefinition(
            attack_id="longsword",
            name="Longsword",
            modifier=7,
            reach_ft=5,
            traits=frozenset({"attack", "melee", "versatile-p"}),
            damage_type="slashing",
            damage_dice=(8,),
            damage_modifier=4,
            item_id="longsword",
        ),
        AttackDefinition(
            attack_id="fist",
            name="Fist",
            modifier=7,
            reach_ft=5,
            traits=frozenset({"attack", "melee", "agile", "finesse", "nonlethal", "unarmed"}),
            damage_type="bludgeoning",
            damage_dice=(4,),
            damage_modifier=4,
        ),
    ),
    kind="pc",
    health_mode=HealthMode.PC,
    abilities=("shield_block", "justice_champion", "justice_retributive_strike", "lay_on_hands", "desperate_prayer"),
    feats=("Natural Skill", "Assurance (Athletics)", "Desperate Prayer"),
    ability_modifiers=(
        ("strength", 4), ("dexterity", 1), ("constitution", 2),
        ("intelligence", 0), ("wisdom", 0), ("charisma", 2),
    ),
    skills=(
        ("athletics", "trained", 7),
        ("crafting", "trained", 3),
        ("diplomacy", "trained", 5),
        ("farming_lore", "trained", 3),
        ("intimidation", "trained", 5),
        ("medicine", "trained", 3),
        ("religion", "trained", 3),
        ("society", "trained", 3),
        ("survival", "trained", 3),
    ),
    saves=(
        ("fortitude", "expert", 7),
        ("reflex", "trained", 4),
        ("will", "expert", 5),
    ),
    proficiencies=(
        ("perception", "trained"),
        ("fortitude", "expert"),
        ("reflex", "trained"),
        ("will", "expert"),
        ("simple_weapons", "trained"),
        ("martial_weapons", "trained"),
        ("unarmed_attacks", "trained"),
        ("unarmored_defense", "trained"),
        ("all_armor", "trained"),
        ("class_dc", "trained"),
        ("spell_attack", "trained"),
        ("spell_dc", "trained"),
    ),
    senses=(),
    vision="ordinary",
    sheet_notes=(
        "Human, Skilled Human (Medicine), Natural Skill (Crafting and Society), Farmhand (Athletics, Farming Lore, Assurance Athletics).",
        "Champion trains Religion and Iomedae grants Intimidation; Diplomacy and Survival are additional trained skills.",
        "15-foot divine aura starts active; suppressing or resuming it takes one concentrate action.",
        "Iomedae grants holy sanctification to every Strike, including fist and retaliation; no spirit damage is added.",
        "Lay on Hands is the selected level-1 devotion spell; focus capacity 1.",
        "Starting equipment: breastplate, longsword, steel shield; 4 gp remains and total Bulk is 4.",
        "No domains, Deific Weapon change, level-3 blessing, or critical specialization is included.",
    ),
    held_items=("longsword", "steel_shield"),
    worn_items=("breastplate",),
    hero_points=1,
    size="medium",
    level=1,
    ancestry="Human",
    heritage="Skilled Human",
    background="Farmhand",
    class_name="Champion",
    deity="Iomedae",
    languages=("Common", "Celestial"),
    class_dc=17,
    focus_spells=(SpontaneousSpellDefinition("lay_on_hands", rank=1),),
    focus_source="devotion",
    focus_points=1,
    focus_capacity=1,
    spell_tradition="divine",
    spell_attack=5,
    spell_dc=15,
    spell_attribute="charisma",
    spell_sanctification="holy",
    armor_category="medium",
    carried_item_bulk=(("breastplate", 2), ("longsword", 1), ("steel_shield", 1)),
    item_instances=(
        ItemInstance("longsword", "longsword"),
        ItemInstance("steel_shield", "steel_shield", hp=20),
    ),
)


JUSTICE_CHAMPION_SETUP = EncounterSetup(
    setup_id="justice_champion_iomedae_vs_guard_dog",
    name="Justice Champion Protects an Ally",
    width=5,
    height=4,
    placements=(
        CreaturePlacement(
            "justice_champion",
            JUSTICE_CHAMPION.definition_id,
            "Justice Champion",
            "blue",
            Position(1, 1),
        ),
        CreaturePlacement(
            "justice_ally",
            "fighter_m_steel_shield_level_1",
            "Champion's Shield Ally",
            "blue",
            Position(1, 2),
        ),
        CreaturePlacement(
            "justice_guard_dog",
            "guard_dog_mc2924",
            "Justice Guard Dog",
            "red",
            Position(2, 1),
        ),
    ),
)
